[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "NODE_ENV=production node index.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
FRONTEND_URL = "https://voting-app-fullstack.netlify.app"
PORT = "3000"
RATE_LIMIT_WINDOW = "15"
RATE_LIMIT_MAX = "100"
TRUST_PROXY = "true"
CORS_ORIGIN = "https://voting-app-fullstack.netlify.app"
CORS_CREDENTIALS = "true"