[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 15
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
minReplicas = 1
maxReplicas = 3

[deploy.lifecycle]
release = "echo 'Starting Voting App Backend'"